export type EmojiItem = {
  emoji: string;
  id: string;
  name: string;
  keywords: string[];
};

/** Curated shortcodes for daily-update notes (`:fire` → 🔥). */
export const EMOJI_SHORTCODES: EmojiItem[] = [
  { emoji: '😀', id: 'grinning', name: 'grinning', keywords: ['happy', 'smile'] },
  { emoji: '😃', id: 'smiley', name: 'smiley', keywords: ['happy', 'smile'] },
  { emoji: '😄', id: 'smile', name: 'smile', keywords: ['happy', 'joy'] },
  { emoji: '😁', id: 'grin', name: 'grin', keywords: ['happy'] },
  { emoji: '😆', id: 'laughing', name: 'laughing', keywords: ['lol', 'happy'] },
  { emoji: '😅', id: 'sweat_smile', name: 'sweat smile', keywords: ['relief', 'nervous'] },
  { emoji: '🤣', id: 'rofl', name: 'rofl', keywords: ['lol', 'laugh'] },
  { emoji: '😂', id: 'joy', name: 'joy', keywords: ['lol', 'tears', 'laugh'] },
  { emoji: '🙂', id: 'slightly_smiling', name: 'slightly smiling', keywords: ['smile'] },
  { emoji: '😉', id: 'wink', name: 'wink', keywords: ['flirt'] },
  { emoji: '😊', id: 'blush', name: 'blush', keywords: ['happy', 'smile'] },
  { emoji: '😇', id: 'innocent', name: 'innocent', keywords: ['angel'] },
  { emoji: '🥰', id: 'smiling_hearts', name: 'smiling hearts', keywords: ['love'] },
  { emoji: '😍', id: 'heart_eyes', name: 'heart eyes', keywords: ['love', 'crush'] },
  { emoji: '🤩', id: 'star_struck', name: 'star struck', keywords: ['wow', 'star'] },
  { emoji: '😘', id: 'kissing_heart', name: 'kissing heart', keywords: ['love', 'kiss'] },
  { emoji: '😋', id: 'yum', name: 'yum', keywords: ['delicious', 'food'] },
  { emoji: '😛', id: 'stuck_out_tongue', name: 'stuck out tongue', keywords: ['playful'] },
  { emoji: '😜', id: 'stuck_out_tongue_winking', name: 'winking tongue', keywords: ['playful'] },
  { emoji: '🤪', id: 'zany', name: 'zany', keywords: ['goofy', 'crazy'] },
  { emoji: '🤨', id: 'raised_eyebrow', name: 'raised eyebrow', keywords: ['skeptical'] },
  { emoji: '🧐', id: 'monocle', name: 'monocle', keywords: ['inspect', 'think'] },
  { emoji: '🤔', id: 'thinking', name: 'thinking', keywords: ['hmm', 'consider'] },
  { emoji: '🤫', id: 'shushing', name: 'shushing', keywords: ['quiet', 'secret'] },
  { emoji: '🤗', id: 'hugs', name: 'hugs', keywords: ['hug', 'care'] },
  { emoji: '🤭', id: 'hand_over_mouth', name: 'hand over mouth', keywords: ['oops', 'secret'] },
  { emoji: '🫡', id: 'salute', name: 'salute', keywords: ['ok', 'yes'] },
  { emoji: '😏', id: 'smirk', name: 'smirk', keywords: ['smug'] },
  { emoji: '😐', id: 'neutral', name: 'neutral', keywords: ['meh'] },
  { emoji: '😑', id: 'expressionless', name: 'expressionless', keywords: ['blank'] },
  { emoji: '😶', id: 'no_mouth', name: 'no mouth', keywords: ['silent'] },
  { emoji: '🙄', id: 'rolling_eyes', name: 'rolling eyes', keywords: ['annoyed'] },
  { emoji: '😬', id: 'grimacing', name: 'grimacing', keywords: ['awkward'] },
  { emoji: '😮‍💨', id: 'exhale', name: 'exhale', keywords: ['relief', 'sigh'] },
  { emoji: '😴', id: 'sleeping', name: 'sleeping', keywords: ['tired', 'zzz'] },
  { emoji: '🤤', id: 'drooling', name: 'drooling', keywords: ['hungry'] },
  { emoji: '😪', id: 'sleepy', name: 'sleepy', keywords: ['tired'] },
  { emoji: '😵', id: 'dizzy', name: 'dizzy', keywords: ['dead', 'knocked'] },
  { emoji: '🤯', id: 'exploding_head', name: 'exploding head', keywords: ['mindblown', 'wow'] },
  { emoji: '🤠', id: 'cowboy', name: 'cowboy', keywords: ['yeehaw'] },
  { emoji: '🥳', id: 'partying', name: 'partying', keywords: ['celebrate', 'party', 'birthday'] },
  { emoji: '😎', id: 'sunglasses', name: 'sunglasses', keywords: ['cool'] },
  { emoji: '🤓', id: 'nerd', name: 'nerd', keywords: ['geek'] },
  { emoji: '🧐', id: 'face_with_monocle', name: 'face with monocle', keywords: ['curious'] },
  { emoji: '😕', id: 'confused', name: 'confused', keywords: ['huh'] },
  { emoji: '😟', id: 'worried', name: 'worried', keywords: ['concern'] },
  { emoji: '🙁', id: 'slightly_frowning', name: 'slightly frowning', keywords: ['sad'] },
  { emoji: '☹️', id: 'frowning', name: 'frowning', keywords: ['sad'] },
  { emoji: '😮', id: 'open_mouth', name: 'open mouth', keywords: ['wow', 'surprised'] },
  { emoji: '😯', id: 'hushed', name: 'hushed', keywords: ['surprise'] },
  { emoji: '😲', id: 'astonished', name: 'astonished', keywords: ['shocked'] },
  { emoji: '😳', id: 'flushed', name: 'flushed', keywords: ['embarrassed'] },
  { emoji: '🥺', id: 'pleading', name: 'pleading', keywords: ['puppy', 'please'] },
  { emoji: '😢', id: 'cry', name: 'cry', keywords: ['sad', 'tear'] },
  { emoji: '😭', id: 'sob', name: 'sob', keywords: ['sad', 'tears'] },
  { emoji: '😤', id: 'triumph', name: 'triumph', keywords: ['frustrated', 'steam'] },
  { emoji: '😠', id: 'angry', name: 'angry', keywords: ['mad'] },
  { emoji: '😡', id: 'rage', name: 'rage', keywords: ['mad', 'angry'] },
  { emoji: '🤬', id: 'cursing', name: 'cursing', keywords: ['mad', 'swear'] },
  { emoji: '😈', id: 'smiling_imp', name: 'smiling imp', keywords: ['devil', 'evil'] },
  { emoji: '👿', id: 'imp', name: 'imp', keywords: ['devil', 'angry'] },
  { emoji: '💀', id: 'skull', name: 'skull', keywords: ['dead', 'danger'] },
  { emoji: '☠️', id: 'skull_crossbones', name: 'skull and crossbones', keywords: ['dead', 'poison'] },
  { emoji: '💩', id: 'poop', name: 'poop', keywords: ['poo', 'shit'] },
  { emoji: '🤡', id: 'clown', name: 'clown', keywords: ['joke'] },
  { emoji: '👻', id: 'ghost', name: 'ghost', keywords: ['boo', 'halloween'] },
  { emoji: '👽', id: 'alien', name: 'alien', keywords: ['ufo'] },
  { emoji: '🤖', id: 'robot', name: 'robot', keywords: ['bot'] },
  { emoji: '😺', id: 'smiley_cat', name: 'smiley cat', keywords: ['cat'] },
  { emoji: '👍', id: 'thumbsup', name: 'thumbs up', keywords: ['yes', 'ok', '+1', 'approve'] },
  { emoji: '👎', id: 'thumbsdown', name: 'thumbs down', keywords: ['no', '-1', 'reject'] },
  { emoji: '👊', id: 'fist', name: 'fist', keywords: ['bump'] },
  { emoji: '✊', id: 'fist_raised', name: 'raised fist', keywords: ['power'] },
  { emoji: '🤛', id: 'left_fist', name: 'left facing fist', keywords: ['bump'] },
  { emoji: '🤜', id: 'right_fist', name: 'right facing fist', keywords: ['bump'] },
  { emoji: '👏', id: 'clap', name: 'clap', keywords: ['applause', 'bravo'] },
  { emoji: '🙌', id: 'raised_hands', name: 'raised hands', keywords: ['celebrate', 'hooray'] },
  { emoji: '👐', id: 'open_hands', name: 'open hands', keywords: ['hands'] },
  { emoji: '🤲', id: 'palms_up', name: 'palms up', keywords: ['pray', 'receive'] },
  { emoji: '🤝', id: 'handshake', name: 'handshake', keywords: ['deal', 'agree', 'meeting'] },
  { emoji: '🙏', id: 'pray', name: 'pray', keywords: ['please', 'thanks', 'namaste'] },
  { emoji: '✍️', id: 'writing', name: 'writing hand', keywords: ['write', 'sign'] },
  { emoji: '💪', id: 'muscle', name: 'muscle', keywords: ['strong', 'flex'] },
  { emoji: '🦾', id: 'mechanical_arm', name: 'mechanical arm', keywords: ['strong', 'robot'] },
  { emoji: '👀', id: 'eyes', name: 'eyes', keywords: ['look', 'see', 'watching'] },
  { emoji: '👁️', id: 'eye', name: 'eye', keywords: ['see'] },
  { emoji: '🧠', id: 'brain', name: 'brain', keywords: ['smart', 'think'] },
  { emoji: '💬', id: 'speech', name: 'speech balloon', keywords: ['comment', 'chat'] },
  { emoji: '💭', id: 'thought', name: 'thought balloon', keywords: ['think'] },
  { emoji: '💯', id: '100', name: 'hundred', keywords: ['perfect', 'score'] },
  { emoji: '💥', id: 'boom', name: 'boom', keywords: ['explosion', 'impact'] },
  { emoji: '💫', id: 'dizzy_star', name: 'dizzy', keywords: ['star'] },
  { emoji: '💦', id: 'sweat_drops', name: 'sweat drops', keywords: ['water'] },
  { emoji: '💨', id: 'dash', name: 'dash', keywords: ['fast', 'wind'] },
  { emoji: '🔥', id: 'fire', name: 'fire', keywords: ['lit', 'hot', 'flame'] },
  { emoji: '⭐', id: 'star', name: 'star', keywords: ['favorite'] },
  { emoji: '🌟', id: 'glowing_star', name: 'glowing star', keywords: ['sparkle'] },
  { emoji: '✨', id: 'sparkles', name: 'sparkles', keywords: ['magic', 'shine'] },
  { emoji: '⚡', id: 'zap', name: 'zap', keywords: ['lightning', 'fast', 'energy'] },
  { emoji: '☀️', id: 'sunny', name: 'sunny', keywords: ['sun', 'weather'] },
  { emoji: '🌈', id: 'rainbow', name: 'rainbow', keywords: ['pride', 'color'] },
  { emoji: '☁️', id: 'cloud', name: 'cloud', keywords: ['weather'] },
  { emoji: '❄️', id: 'snowflake', name: 'snowflake', keywords: ['cold', 'winter'] },
  { emoji: '💧', id: 'droplet', name: 'droplet', keywords: ['water'] },
  { emoji: '🎉', id: 'tada', name: 'tada', keywords: ['party', 'celebrate', 'confetti'] },
  { emoji: '🎊', id: 'confetti', name: 'confetti ball', keywords: ['party', 'celebrate'] },
  { emoji: '🎈', id: 'balloon', name: 'balloon', keywords: ['party'] },
  { emoji: '🎁', id: 'gift', name: 'gift', keywords: ['present', 'birthday'] },
  { emoji: '🏆', id: 'trophy', name: 'trophy', keywords: ['win', 'award'] },
  { emoji: '🥇', id: 'first_place', name: 'first place', keywords: ['gold', 'win'] },
  { emoji: '🥈', id: 'second_place', name: 'second place', keywords: ['silver'] },
  { emoji: '🥉', id: 'third_place', name: 'third place', keywords: ['bronze'] },
  { emoji: '🎯', id: 'dart', name: 'direct hit', keywords: ['target', 'goal'] },
  { emoji: '🚀', id: 'rocket', name: 'rocket', keywords: ['launch', 'ship', 'deploy'] },
  { emoji: '💡', id: 'bulb', name: 'bulb', keywords: ['idea', 'light'] },
  { emoji: '📌', id: 'pushpin', name: 'pushpin', keywords: ['pin', 'important'] },
  { emoji: '📍', id: 'round_pushpin', name: 'round pushpin', keywords: ['location', 'pin'] },
  { emoji: '📎', id: 'paperclip', name: 'paperclip', keywords: ['attach'] },
  { emoji: '🔗', id: 'link', name: 'link', keywords: ['url', 'chain'] },
  { emoji: '📝', id: 'memo', name: 'memo', keywords: ['note', 'write'] },
  { emoji: '📁', id: 'folder', name: 'folder', keywords: ['files'] },
  { emoji: '📂', id: 'open_folder', name: 'open folder', keywords: ['files'] },
  { emoji: '📅', id: 'calendar', name: 'calendar', keywords: ['date', 'schedule'] },
  { emoji: '✅', id: 'white_check_mark', name: 'check mark', keywords: ['done', 'yes', 'complete', 'ok'] },
  { emoji: '☑️', id: 'ballot_box', name: 'ballot box', keywords: ['done', 'check'] },
  { emoji: '✔️', id: 'heavy_check', name: 'heavy check', keywords: ['done', 'yes'] },
  { emoji: '❌', id: 'x', name: 'cross mark', keywords: ['no', 'wrong', 'delete'] },
  { emoji: '❎', id: 'negative_squared_cross', name: 'cross mark button', keywords: ['no'] },
  { emoji: '❗', id: 'exclamation', name: 'exclamation', keywords: ['alert', 'important'] },
  { emoji: '❓', id: 'question', name: 'question', keywords: ['help', 'ask'] },
  { emoji: '⚠️', id: 'warning', name: 'warning', keywords: ['caution', 'alert'] },
  { emoji: '🚫', id: 'no_entry', name: 'prohibited', keywords: ['block', 'stop'] },
  { emoji: '🔴', id: 'red_circle', name: 'red circle', keywords: ['status', 'dot'] },
  { emoji: '🟠', id: 'orange_circle', name: 'orange circle', keywords: ['status'] },
  { emoji: '🟡', id: 'yellow_circle', name: 'yellow circle', keywords: ['status'] },
  { emoji: '🟢', id: 'green_circle', name: 'green circle', keywords: ['status', 'ok'] },
  { emoji: '🔵', id: 'blue_circle', name: 'blue circle', keywords: ['status'] },
  { emoji: '🟣', id: 'purple_circle', name: 'purple circle', keywords: ['status'] },
  { emoji: '⬛', id: 'black_square', name: 'black square', keywords: ['block'] },
  { emoji: '⬜', id: 'white_square', name: 'white square', keywords: ['block'] },
  { emoji: '❤️', id: 'heart', name: 'heart', keywords: ['love', 'red'] },
  { emoji: '🧡', id: 'orange_heart', name: 'orange heart', keywords: ['love'] },
  { emoji: '💛', id: 'yellow_heart', name: 'yellow heart', keywords: ['love'] },
  { emoji: '💚', id: 'green_heart', name: 'green heart', keywords: ['love'] },
  { emoji: '💙', id: 'blue_heart', name: 'blue heart', keywords: ['love'] },
  { emoji: '💜', id: 'purple_heart', name: 'purple heart', keywords: ['love'] },
  { emoji: '🖤', id: 'black_heart', name: 'black heart', keywords: ['love'] },
  { emoji: '🤍', id: 'white_heart', name: 'white heart', keywords: ['love'] },
  { emoji: '💔', id: 'broken_heart', name: 'broken heart', keywords: ['sad', 'love'] },
  { emoji: '💕', id: 'two_hearts', name: 'two hearts', keywords: ['love'] },
  { emoji: '💞', id: 'revolving_hearts', name: 'revolving hearts', keywords: ['love'] },
  { emoji: '💓', id: 'heartbeat', name: 'heartbeat', keywords: ['love'] },
  { emoji: '💗', id: 'growing_heart', name: 'growing heart', keywords: ['love'] },
  { emoji: '💖', id: 'sparkling_heart', name: 'sparkling heart', keywords: ['love'] },
  { emoji: '💘', id: 'cupid', name: 'cupid', keywords: ['love'] },
  { emoji: '💝', id: 'gift_heart', name: 'gift heart', keywords: ['love', 'gift'] },
  { emoji: '☕', id: 'coffee', name: 'coffee', keywords: ['tea', 'cafe'] },
  { emoji: '🍵', id: 'tea', name: 'tea', keywords: ['green', 'drink'] },
  { emoji: '🍺', id: 'beer', name: 'beer', keywords: ['drink', 'cheers'] },
  { emoji: '🍻', id: 'beers', name: 'beers', keywords: ['cheers', 'drink'] },
  { emoji: '🍕', id: 'pizza', name: 'pizza', keywords: ['food'] },
  { emoji: '🍔', id: 'burger', name: 'burger', keywords: ['food', 'hamburger'] },
  { emoji: '🍩', id: 'doughnut', name: 'doughnut', keywords: ['food', 'sweet'] },
  { emoji: '🍪', id: 'cookie', name: 'cookie', keywords: ['food', 'sweet'] },
  { emoji: '🎂', id: 'birthday', name: 'birthday', keywords: ['cake', 'party'] },
  { emoji: '🏠', id: 'house', name: 'house', keywords: ['home'] },
  { emoji: '🏢', id: 'office', name: 'office', keywords: ['work', 'building'] },
  { emoji: '💻', id: 'computer', name: 'computer', keywords: ['laptop', 'work', 'code'] },
  { emoji: '🖥️', id: 'desktop', name: 'desktop', keywords: ['computer', 'monitor'] },
  { emoji: '📱', id: 'iphone', name: 'mobile phone', keywords: ['phone', 'mobile'] },
  { emoji: '⌨️', id: 'keyboard', name: 'keyboard', keywords: ['type', 'code'] },
  { emoji: '🛠️', id: 'tools', name: 'tools', keywords: ['fix', 'build', 'wrench'] },
  { emoji: '🔧', id: 'wrench', name: 'wrench', keywords: ['fix', 'tool'] },
  { emoji: '⚙️', id: 'gear', name: 'gear', keywords: ['settings', 'config'] },
  { emoji: '🧱', id: 'bricks', name: 'bricks', keywords: ['build'] },
  { emoji: '📊', id: 'bar_chart', name: 'bar chart', keywords: ['stats', 'data'] },
  { emoji: '📈', id: 'chart_up', name: 'chart increasing', keywords: ['growth', 'up'] },
  { emoji: '📉', id: 'chart_down', name: 'chart decreasing', keywords: ['down'] },
  { emoji: '🧪', id: 'test_tube', name: 'test tube', keywords: ['test', 'science', 'qa'] },
  { emoji: '🐛', id: 'bug', name: 'bug', keywords: ['insect', 'error', 'debug'] },
  { emoji: '🐝', id: 'bee', name: 'bee', keywords: ['busy'] },
  { emoji: '🦄', id: 'unicorn', name: 'unicorn', keywords: ['magic'] },
  { emoji: '🐶', id: 'dog', name: 'dog', keywords: ['puppy', 'pet'] },
  { emoji: '🐱', id: 'cat', name: 'cat', keywords: ['kitten', 'pet'] },
  { emoji: '🦊', id: 'fox', name: 'fox', keywords: ['animal'] },
  { emoji: '🐻', id: 'bear', name: 'bear', keywords: ['animal'] },
  { emoji: '🐼', id: 'panda', name: 'panda', keywords: ['animal'] },
  { emoji: '🐨', id: 'koala', name: 'koala', keywords: ['animal'] },
  { emoji: '🐯', id: 'tiger', name: 'tiger', keywords: ['animal'] },
  { emoji: '🦁', id: 'lion', name: 'lion', keywords: ['animal'] },
  { emoji: '🐮', id: 'cow', name: 'cow', keywords: ['animal'] },
  { emoji: '🐷', id: 'pig', name: 'pig', keywords: ['animal'] },
  { emoji: '🐸', id: 'frog', name: 'frog', keywords: ['animal'] },
  { emoji: '🐵', id: 'monkey', name: 'monkey', keywords: ['animal'] },
  { emoji: '🐔', id: 'chicken', name: 'chicken', keywords: ['animal'] },
  { emoji: '🐧', id: 'penguin', name: 'penguin', keywords: ['animal'] },
  { emoji: '🐦', id: 'bird', name: 'bird', keywords: ['animal'] },
  { emoji: '🐤', id: 'hatching_chick', name: 'chick', keywords: ['bird', 'baby'] },
  { emoji: '🐣', id: 'hatched_chick', name: 'hatching chick', keywords: ['bird'] },
  { emoji: '🐥', id: 'baby_chick', name: 'baby chick', keywords: ['bird'] },
  { emoji: '🦆', id: 'duck', name: 'duck', keywords: ['bird'] },
  { emoji: '🦅', id: 'eagle', name: 'eagle', keywords: ['bird'] },
  { emoji: '🦉', id: 'owl', name: 'owl', keywords: ['bird', 'wise'] },
  { emoji: '🦇', id: 'bat', name: 'bat', keywords: ['halloween'] },
  { emoji: '🐺', id: 'wolf', name: 'wolf', keywords: ['animal'] },
  { emoji: '🐗', id: 'boar', name: 'boar', keywords: ['animal'] },
  { emoji: '🐴', id: 'horse', name: 'horse', keywords: ['animal'] },
  { emoji: '🦄', id: 'unicorn_face', name: 'unicorn face', keywords: ['magic'] },
  { emoji: '🐝', id: 'honeybee', name: 'honeybee', keywords: ['busy'] },
  { emoji: '🪱', id: 'worm', name: 'worm', keywords: ['bug'] },
  { emoji: '🌸', id: 'cherry_blossom', name: 'cherry blossom', keywords: ['flower', 'spring'] },
  { emoji: '🌺', id: 'hibiscus', name: 'hibiscus', keywords: ['flower'] },
  { emoji: '🌻', id: 'sunflower', name: 'sunflower', keywords: ['flower'] },
  { emoji: '🌹', id: 'rose', name: 'rose', keywords: ['flower', 'love'] },
  { emoji: '🌷', id: 'tulip', name: 'tulip', keywords: ['flower'] },
  { emoji: '🌱', id: 'seedling', name: 'seedling', keywords: ['plant', 'grow'] },
  { emoji: '🌲', id: 'evergreen', name: 'evergreen', keywords: ['tree'] },
  { emoji: '🌳', id: 'deciduous', name: 'deciduous tree', keywords: ['tree'] },
  { emoji: '🌴', id: 'palm', name: 'palm tree', keywords: ['tree', 'beach'] },
  { emoji: '🍀', id: 'four_leaf_clover', name: 'four leaf clover', keywords: ['luck'] },
  { emoji: '🍁', id: 'maple_leaf', name: 'maple leaf', keywords: ['fall', 'autumn'] },
  { emoji: '🌊', id: 'ocean', name: 'ocean', keywords: ['wave', 'water'] },
  { emoji: '🎵', id: 'musical_note', name: 'musical note', keywords: ['music'] },
  { emoji: '🎶', id: 'notes', name: 'notes', keywords: ['music'] },
  { emoji: '🔔', id: 'bell', name: 'bell', keywords: ['notify', 'alert'] },
  { emoji: '🔕', id: 'no_bell', name: 'muted bell', keywords: ['mute', 'silent'] },
  { emoji: '📣', id: 'mega', name: 'megaphone', keywords: ['announce'] },
  { emoji: '⏰', id: 'alarm', name: 'alarm clock', keywords: ['time', 'wake'] },
  { emoji: '⏱️', id: 'stopwatch', name: 'stopwatch', keywords: ['time', 'timer'] },
  { emoji: '⏳', id: 'hourglass', name: 'hourglass', keywords: ['wait', 'time'] },
  { emoji: '🔄', id: 'arrows_counterclockwise', name: 'counterclockwise arrows', keywords: ['refresh', 'sync', 'reload'] },
  { emoji: '➡️', id: 'arrow_right', name: 'right arrow', keywords: ['next'] },
  { emoji: '⬅️', id: 'arrow_left', name: 'left arrow', keywords: ['back'] },
  { emoji: '⬆️', id: 'arrow_up', name: 'up arrow', keywords: ['up'] },
  { emoji: '⬇️', id: 'arrow_down', name: 'down arrow', keywords: ['down'] },
  { emoji: '↩️', id: 'leftwards_arrow_with_hook', name: 'return', keywords: ['reply', 'enter'] },
  { emoji: '🔀', id: 'twisted_rightwards_arrows', name: 'shuffle', keywords: ['random'] },
  { emoji: '▶️', id: 'arrow_forward', name: 'play', keywords: ['start'] },
  { emoji: '⏸️', id: 'pause', name: 'pause', keywords: ['stop'] },
  { emoji: '⏹️', id: 'stop_button', name: 'stop', keywords: ['end'] },
  { emoji: '🆕', id: 'new', name: 'new', keywords: ['badge'] },
  { emoji: '🆙', id: 'up', name: 'up', keywords: ['badge'] },
  { emoji: '🆒', id: 'cool', name: 'cool', keywords: ['badge'] },
  { emoji: '🆗', id: 'ok', name: 'ok', keywords: ['badge', 'yes'] },
  { emoji: '🆘', id: 'sos', name: 'sos', keywords: ['help', 'emergency'] },
];

const POPULAR_IDS = [
  'thumbsup',
  'fire',
  'tada',
  'white_check_mark',
  'rocket',
  'bulb',
  'heart',
  'clap',
  'eyes',
  'pray',
  'smile',
  'thinking',
  'warning',
  'bug',
  'computer',
  'coffee',
];

export function matchEmojis(query: string, limit = 24): EmojiItem[] {
  const q = query.trim().toLowerCase().replace(/^:+|:+$/g, '');
  if (!q) {
    const popular = POPULAR_IDS.map((id) => EMOJI_SHORTCODES.find((e) => e.id === id)).filter(
      (e): e is EmojiItem => !!e,
    );
    return popular.slice(0, limit);
  }

  const scored = EMOJI_SHORTCODES.map((item) => {
    const id = item.id.toLowerCase();
    const name = item.name.toLowerCase();
    const keys = item.keywords.map((k) => k.toLowerCase());
    let score = 0;
    if (id === q || name === q) score = 100;
    else if (id.startsWith(q) || name.startsWith(q)) score = 80;
    else if (id.includes(q) || name.includes(q)) score = 50;
    else if (keys.some((k) => k.startsWith(q))) score = 40;
    else if (keys.some((k) => k.includes(q))) score = 20;
    return { item, score };
  })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score || a.item.id.localeCompare(b.item.id));

  return scored.slice(0, limit).map((x) => x.item);
}
